# Site settings
title: thebernardlim
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software development. Fitness. Arsenal FC.
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username: github.com/thebernardlim
testtest: sdsdsds
paginate: 8
collections:
- crossfit


# Dependencies
markdown:         kramdown
highlighter:      none

# Permalinks
permalink:        pretty

gems: [jekyll-paginate]
